# Generated by Django 4.2.7 on 2024-02-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='region',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/pofile/%Y/%m/%d/'),
        ),
    ]
