# Generated by Django 4.2.7 on 2024-02-17 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sitetest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons',
            name='author',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='persons',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categ', to='sitetest.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='persons',
            name='country',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countri', to='sitetest.country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='persons',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='sitetest.tagpost', verbose_name='Tags'),
        ),
    ]
