# Generated by Django 4.2.7 on 2023-12-14 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitetest', '0006_alter_persons_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persons',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
