# Generated by Django 4.2.7 on 2023-12-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitetest', '0008_alter_persons_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persons',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Not Published'), (1, 'Published')], default=0),
        ),
    ]
