# Generated by Django 4.2.7 on 2023-12-15 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitetest', '0010_category_persons_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persons',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sitetest.category'),
        ),
    ]
