# Generated by Django 4.2.7 on 2023-12-19 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitetest', '0014_alter_persons_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
