# Generated by Django 4.2.7 on 2024-01-08 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitetest', '0015_alter_country_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persons',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categ', to='sitetest.category'),
        ),
    ]
