# Generated by Django 4.2.7 on 2024-02-03 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitetest', '0016_alter_persons_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads_model')),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Catefories'},
        ),
        migrations.AlterModelOptions(
            name='persons',
            options={'verbose_name_plural': 'Person'},
        ),
        migrations.AddField(
            model_name='persons',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='photo', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categ', to='sitetest.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='content',
            field=models.TextField(blank=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='country',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countri', to='sitetest.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='is_published',
            field=models.BooleanField(choices=[(False, 'Not Published'), (True, 'Published')], default=0, verbose_name='Published Status'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='sitetest.tagpost', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Time of creation'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Last update'),
        ),
        migrations.AlterField(
            model_name='persons',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
    ]
